version: "3.2"

services:
  rabbitmq-ride:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ride
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=senhadev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq-network
networks:
  rabbitmq-network:
    driver: bridge
